### ISSUE TITLE
Swift Error

### ISSUE THREAD

**Issue by rmagnuson** [aradianoff/recatpchacontact#48]
Swift_TransportException
Expected response code 220 but got code "", with message ""

Followed install instructions, put keys in, etc. Added new page with form. Tested form. Added pertinent info (name, email, test text), hit recaptcha, hit submit. Got the above error.

**Comment by fauzie** [comment]
+1

```
grav.CRITICAL: Expected response code 220 but got code "", with message "" - Trace: 
#0 /usr/html/user/plugins/email/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(289): Swift_Transport_AbstractSmtpTransport->_assertResponseCode('', Array) 
#1 /usr/html/user/plugins/email/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(117): Swift_Transport_AbstractSmtpTransport->_readGreeting() 
#2 /usr/html/user/plugins/email/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/SendmailTransport.php(51): Swift_Transport_AbstractSmtpTransport->start() 
#3 /usr/html/user/plugins/email/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_SendmailTransport->start() 
#4 /usr/html/user/plugins/email/classes/Email.php(104): Swift_Mailer->send(Object(Swift_Message)) 
#5 /usr/html/user/plugins/recaptchacontact/recaptchacontact.php(280): Grav\Plugin\Email\Email->send(Object(Swift_Message)) 
#6 /usr/html/user/plugins/recaptchacontact/recaptchacontact.php(164): Grav\Plugin\ReCaptchaContactPlugin->sendEmail() 
#7 /usr/html/user/plugins/recaptchacontact/recaptchacontact.php(138): Grav\Plugin\ReCaptchaContactPlugin->processFormAction(Object(Grav\Common\Uri)) 
#8 /usr/html/user/plugins/recaptchacontact/recaptchacontact.php(90): Grav\Plugin\ReCaptchaContactPlugin->setupRecaptchaContact(Object(Grav\Common\Page\Page), true) 
#9 /usr/html/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Grav\Plugin\ReCaptchaContactPlugin->onPageInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onPageInitializ...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) 
#10 /usr/html/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPageInitializ...', Object(RocketTheme\Toolbox\Event\Event)) 
#11 /usr/html/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onPageInitializ...', Object(RocketTheme\Toolbox\Event\Event)) 
#12 /usr/html/system/src/Grav/Common/Grav.php(279): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onPageInitializ...', Object(RocketTheme\Toolbox\Event\Event)) 
#13 /usr/html/system/src/Grav/Common/Processors/PagesProcessor.php(26): Grav\Common\Grav->fireEvent('onPageInitializ...', Object(RocketTheme\Toolbox\Event\Event)) 
#14 /usr/html/system/src/Grav/Common/Grav.php(131): Grav\Common\Processors\PagesProcessor->process() 
#15 /usr/html/system/src/Grav/Common/Grav.php(370): Grav\Common\Grav->Grav\Common\{closure}() 
#16 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('pages', 'Pages', Object(Closure)) 
#17 /usr/html/system/src/Grav/Common/Grav.php(346): call_user_func_array(Object(Closure), Array) 
#18 /usr/html/system/src/Grav/Common/Grav.php(132): Grav\Common\Grav->__call('measureTime', Array) 
#19 /usr/html/index.php(54): Grav\Common\Grav->process() 
#20 {main} [] []
```

How to fix that?
